contracts:
  - contractAddress: "<input contract address>"
    duneTableName: "dataset_<contract name>"
    duneTableNamespace: "<handle that API key belongs to>"
    contractDeployedBlock: 0

  # ====== Examples ======

  # - contractAddress: "0x33128a8fC17869897dcE68Ed026d694621f6FDfD" # UniswapV3 PoolFactory
  #   duneTableName: "dataset_jackie_byop_mvp_uniswapv3_pool_factory_base_all_events_raw_updated"
  #   duneTableNamespace: "dune"
  #   contractDeployedBlock: 1371680

  # - contractAddress: "0xd0b53D9277642d899DF5C87A3966A349A798F224" # UniswapV3 ETH/USDC 10
  #   duneTableName: "dataset_jackie_byop_mvp_uniswapv3_ethusdc_10_base_all_events_raw_updated"
  #   duneTableNamespace: "dune"
  #   contractDeployedBlock: 3620407
